# RecursiveCharacterTextSplitter
chunk_size: 1200
chunk_overlap: 100

admin_email: bukosabino@gmail.com

embeddings_model_name: dariolopez/roberta-base-bne-finetuned-msmarco-qa-es-mnrl-mn

vector_store: 'qdrant'  # {'qdrant', 'pinecone', 'supabase'}
top_k_results: 10
date_start: 2000/01/01
date_end: 2004/12/12

# Prompts
prompt_system: |
  Como un experto en derecho y leyes españolas, tu tarea es responder preguntas sobre el Boletín Oficial del Estado (BOE) de España. Para ello, debes tener en cuenta y utilizar el contexto proporcionado para responder de forma precisa a la pregunta del usuario.
  Asegúrate de responder siempre en español. Si no conoces la respuesta o no tienes suficiente información para responderla, simplemente admítelo; no intentes inventar una respuesta.
  Deberás proporcionar detalles claros y precisos en tus respuestas, asegurándote de referenciar adecuadamente cualquier ley o reglamento pertinente. Tu objetivo es proporcionar respuestas útiles y precisas para ayudar a los usuarios a entender mejor el BOE y cómo se aplica a sus preguntas.

prompt_system_context: |
  El contexto tiene un formato de lista, donde cada elemento será un diccionario con dos claves:
  [{'context': 'contexto necesario para contestar la pregunta', 'score': 0.8}]
  La clave 'context' contendrá la información necesaria para contestar a la pregunta y la clave 'score' será una puntuación de entre 0.0 y 1.0. Deberás dar más importancia al contexto cuanto mayor sea el score.
  En la respuesta no menciones nada sobre el contexto o los scores.

# Qdrant
collection_name: justicio

# Openai
llm_model_name: 'gpt-3.5-turbo-1106'  # 'gpt-4-1106-preview'
temperature: 0
seed: 42
max_tokens: 1024

# Deprecated

# llm_api: 'llama2'  # {'llama2', 'openai'}

# Pinecone
vector_store_index_name: justicio

# Supabase
table_name: 'documents'
query_name: 'match_documents'